import { globSync, writeFileSync } from 'fs';
import { basename } from 'path';

const configs = globSync('src/app/config/*ModuleConfig.ts');

const configNames = configs.map((configPath) => basename(configPath, '.ts'));

const imports = configNames
  .map((configName) => `import ${configName} from '@app/config/${configName}';`)
  .join('\n');

const arrayItems = configNames
  .map((configName) => `  ${configName},`)
  .join('\n');

const output = `/* This file is auto-generated by preBuild.ts. Do not edit manually. */

${imports}

export const moduleConfigLoaders = [
${arrayItems}
] as const;
`;

writeFileSync('src/base/config/moduleConfigLoaders.ts', `${output}\n\n`);
