/* This file is auto-generated by preBuild.ts. Do not edit manually. */

import appModuleConfig from '@app/config/appModuleConfig';
import cmsModuleConfig from '@app/config/cmsModuleConfig';
import mailModuleConfig from '@app/config/mailModuleConfig';
import securityModuleConfig from '@app/config/securityModuleConfig';
import technobabbleModuleConfig from '@app/config/technobabbleModuleConfig';
import templatingModuleConfig from '@app/config/templatingModuleConfig';

export const moduleConfigLoaders = [
  appModuleConfig,
  cmsModuleConfig,
  mailModuleConfig,
  securityModuleConfig,
  technobabbleModuleConfig,
  templatingModuleConfig,
] as const;
